using Age.Crypto;
using Age.Format;
using Age.Recipients;
using Xunit;

namespace Age.Tests;

/// <summary>
/// Guards on the backported paths that the ordinary round-trip tests never reach: a custom
/// identity returning the wrong-sized file key, random access over a truncated payload, and the
/// encode overload's own bounds check.
/// </summary>
public class BackportEdgeCaseTests
{
    // A custom or plugin identity is caller-supplied code and can hand back anything. Accepting a
    // wrong-sized key would derive garbage rather than fail, so the guard runs before the header
    // MAC is verified and must clear the key on the way out (S9).
    private sealed class WrongSizedKeyIdentity : IIdentity
    {
        public byte[]? Unwrap(Stanza stanza) => new byte[15];
    }

    // age-plugin.md:227 requires the exact same label set across every stanza wrapping one file
    // key. Wrap throws, so these also prove the check runs before any wrapping happens.
    private sealed class LabelledRecipient(string? label) : IRecipient
    {
        public string? Label => label;

        public Stanza Wrap(ReadOnlySpan<byte> fileKey) =>
            throw new NotSupportedException("label check should have rejected this first");
    }

    [Theory]
    [InlineData("postquantum", null)]
    [InlineData(null, "postquantum")]
    [InlineData("postquantum", "acme-internal")]
    public void MixingPostQuantumWithAnythingElse_NamesWhatIsLost(string? a, string? b)
    {
        var ex = Assert.Throws<AgeException>(() => Encrypt(a, b));

        Assert.Contains("post-quantum and classical", ex.Message, StringComparison.Ordinal);
        Assert.Contains("quantum computer", ex.Message, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("acme-internal", null, "\"acme-internal\"", "none")]
    [InlineData("acme-internal", "globex", "\"acme-internal\"", "\"globex\"")]
    public void MixingOtherLabels_NamesBothSides(string? a, string? b, string expectedA, string expectedB)
    {
        var ex = Assert.Throws<AgeException>(() => Encrypt(a, b));

        Assert.Contains(expectedA, ex.Message, StringComparison.Ordinal);
        Assert.Contains(expectedB, ex.Message, StringComparison.Ordinal);
        Assert.DoesNotContain("quantum", ex.Message, StringComparison.Ordinal);
    }

    private static void Encrypt(string? a, string? b)
    {
        using var input = new MemoryStream("x"u8.ToArray());
        using var output = new MemoryStream();

        AgeEncrypt.Encrypt(input, output, new LabelledRecipient(a), new LabelledRecipient(b));
    }

    [Fact]
    public void FileKey_ZeroesOnDispose()
    {
        var key = FileKey.Fresh();
        var live = key.Bytes.ToArray();

        Assert.Contains(live, b => b != 0);

        key.Dispose();

        Assert.Throws<ObjectDisposedException>(() => key.Bytes.ToArray());
        key.Dispose(); // idempotent
    }

    [Fact]
    public void FileKey_AdoptZeroesWhatItRejects()
    {
        var wrongSized = new byte[15];
        Array.Fill(wrongSized, (byte)0xAB);

        Assert.Throws<AgeHeaderException>(() => FileKey.Adopt(wrongSized));

        // The rejected array came from caller-supplied identity code and still held key
        // material; refusing it must not mean abandoning it.
        Assert.DoesNotContain(wrongSized, b => b != 0);
    }

    [Fact]
    public void IdentityReturningAWrongSizedFileKey_IsRejected()
    {
        using var real = X25519Identity.Generate();

        using var input = new MemoryStream("edge"u8.ToArray());
        using var encrypted = new MemoryStream();
        AgeEncrypt.Encrypt(input, encrypted, real.Recipient);

        using var source = new MemoryStream(encrypted.ToArray());
        using var output = new MemoryStream();

        var ex = Assert.Throws<AgeHeaderException>(
            () => AgeEncrypt.Decrypt(source, output, new WrongSizedKeyIdentity()));

        Assert.Contains("file key must be", ex.Message, StringComparison.Ordinal);
    }

    // S9 — a recipient that throws mid-wrap is routine: a plugin binary missing, a user declining
    // a touch prompt. The file key is already generated by then, so every one of those paths has
    // to clear it. Captured here by handing the recipient the key it is asked to wrap and then
    // throwing, so the test can inspect what the library left behind.
    private sealed class ThrowingRecipient : IRecipient
    {
        public byte[]? SeenFileKey { get; private set; }

        public string? Label => null;

        public Stanza Wrap(ReadOnlySpan<byte> fileKey)
        {
            SeenFileKey = fileKey.ToArray();
            throw new AgePluginException("recipient declined");
        }
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void WhenARecipientThrows_TheFileKeyIsCleared(bool detached)
    {
        var recipient = new ThrowingRecipient();

        Assert.Throws<AgePluginException>(() =>
        {
            using var input = new MemoryStream("x"u8.ToArray());
            using var a = new MemoryStream();
            using var b = new MemoryStream();

            if (detached)
                AgeEncrypt.EncryptDetached(input, a, b, recipient);
            else
                AgeEncrypt.Encrypt(input, a, recipient);
        });

        // The recipient saw a real, non-zero key...
        Assert.NotNull(recipient.SeenFileKey);
        Assert.Contains(recipient.SeenFileKey!, b => b != 0);

        // ...and the library's own copy must not still be live. Verified by wrapping again and
        // confirming a fresh key each time, so a retained buffer would be visible as a repeat.
        var second = new ThrowingRecipient();

        Assert.Throws<AgePluginException>(() =>
        {
            using var input = new MemoryStream("x"u8.ToArray());
            using var a = new MemoryStream();
            AgeEncrypt.Encrypt(input, a, second);
        });

        Assert.NotEqual(recipient.SeenFileKey, second.SeenFileKey);
    }

    // --- Random access over damaged payloads: the same rejections the forward-only path makes ---

    private static byte[] Encrypted(X25519Identity identity, int size)
    {
        var plaintext = new byte[size];
        for (var i = 0; i < size; i++) plaintext[i] = (byte)(i * 31 % 251);

        using var input = new MemoryStream(plaintext);
        using var output = new MemoryStream();
        AgeEncrypt.Encrypt(input, output, identity.Recipient);

        return output.ToArray();
    }

    [Fact]
    public void RandomAccess_OverAPayloadWithNoChunks_IsRejected()
    {
        using var identity = X25519Identity.Generate();
        var file = Encrypted(identity, 32);

        // Keep the header and the 16-byte payload nonce, drop every chunk.
        var headerEnd = FindPayloadStart(file);
        var truncated = file[..(headerEnd + 16)];

        Assert.Throws<AgePayloadException>(() =>
        {
            using var source = new MemoryStream(truncated);
            using var reader = new AgeRandomAccess(source, identity);
        });
    }

    [Fact]
    public void RandomAccess_OverAChunkTooSmallForItsTag_IsRejected()
    {
        using var identity = X25519Identity.Generate();
        var file = Encrypted(identity, 32);

        // A payload of fewer than 16 bytes cannot even hold an authentication tag.
        var headerEnd = FindPayloadStart(file);
        var truncated = file[..(headerEnd + 16 + 8)];

        Assert.Throws<AgePayloadException>(() =>
        {
            using var source = new MemoryStream(truncated);
            using var reader = new AgeRandomAccess(source, identity);
        });
    }

    // The payload begins immediately after the header's MAC line.
    private static int FindPayloadStart(byte[] file)
    {
        var text = System.Text.Encoding.ASCII.GetString(file);
        var macLine = text.IndexOf("--- ", StringComparison.Ordinal);

        return text.IndexOf('\n', macLine) + 1;
    }

    // H6 — deriving the post-quantum recipient runs a full ML-KEM-768 key generation, and it was
    // re-run on every access, so decrypting an N-stanza header cost N keygens. Caching makes that
    // one. A bounded constant factor rather than a denial-of-service vector, but free to fix.
    [Fact]
    public void PostQuantumRecipient_IsDerivedOnceAndReused()
    {
        using var identity = MlKem768X25519Identity.Generate();

        var first = identity.Recipient;
        var second = identity.Recipient;

        Assert.Same(first, second);
        Assert.Equal(first.ToString(), second.ToString());
    }

    [Fact]
    public void PostQuantumRecipient_IsStillGuardedAfterDispose()
    {
        var identity = MlKem768X25519Identity.Generate();
        _ = identity.Recipient; // populate the cache first

        identity.Dispose();

        // The cache must not become a way to reach a disposed identity's derived key.
        Assert.Throws<ObjectDisposedException>(() => identity.Recipient);
    }

    // --- The span-filling encoder's own guard ---

    [Fact]
    public void EncodeIntoTooSmallABuffer_Throws()
    {
        var data = new byte[32];

        Assert.Throws<InvalidOperationException>(() => Base64Unpadded.Encode(data, new char[4]));
    }

    [Fact]
    public void EncodeIntoAnExactlySizedBuffer_Works()
    {
        var data = new byte[16];
        var destination = new char[Base64Unpadded.MaxEncodedLength(data.Length)];

        var written = Base64Unpadded.Encode(data, destination);

        Assert.Equal(Base64Unpadded.Encode(data), new string(destination, 0, written));
    }

    [Fact]
    public void EncodeOfNothingWritesNothing()
    {
        Assert.Equal(0, Base64Unpadded.Encode([], new char[4]));
    }
}
